In [1]:
import numpy as np 

from sklearn import datasets

cancer=datasets.load_breast_cancer()

In [2]:
#print the features name

print("Features:",cancer.feature_names)

print("Labels:",cancer.target_names)

Features: ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Labels: ['malignant' 'benign']


In [4]:
#top 5 recoreds

print(cancer.data[0:5])



[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425e-01 2.839e-01 2.414

In [5]:
from sklearn.model_selection import train_test_split 

X_train,X_test,y_train,y_test=train_test_split(cancer.data,cancer.target,test_size=0.3,random_state=109)

In [6]:
from sklearn import svm
clf=svm.SVC(kernel='linear')

clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)


In [7]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.9649122807017544


In [8]:
import pandas as pd 

In [9]:
irisdata=datasets.load_iris



In [10]:
url= "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
colnames=['sepal-length','sepal-width','petal-length','petal-width','Class']

irisdata=pd.read_csv(url,names=colnames)

In [11]:
irisdata

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [13]:
X=irisdata.drop('Class',axis=1)
y=irisdata['Class']

In [14]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)


In [16]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='poly',degree=1)
svclassifier.fit(X_train,y_train)

SVC(degree=1, kernel='poly')

In [17]:
y_pred=svclassifier.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred)*100)
print(confusion_matrix(y_test,y_pred))

Accuracy: 100.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [19]:
svclassifier=SVC(kernel='rbf',gamma=0.1)
svclassifier.fit(X_train,y_train)

SVC(gamma=0.1)

In [20]:
y_pred=svclassifier.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred)*100)
print(confusion_matrix(y_test,y_pred))

Accuracy: 100.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
